### ISSUE TITLE
Support docker build

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/insulatr#11]
Multiple features:

1. Allow mounting of Docker socket when certain parameter is present, e.g. `--allow-docker-socket`. Build steps with `mount_docker_socket: true` get it:

  ```yaml
  steps:
    - name: dood
      image: docker:stable
      mount_docker_socket: true
      commands:
        - docker version
  ```

1. When `--allow-privileged` is present, a service can specify `privileged: true`:

  ```yaml
  services:
    - name: dind
      image: docker:dind
      privileged: true
  steps:
    - name: build
      image: docker
      environment:
        - DOCKER_HOST=tcp://dind:2375
      commands:
        - docker version
  ```

~~Allow privileged build steps as well? Probably...~~
