### ISSUE TITLE
Create file from build definition

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/insulatr#22]
Something like...

```yaml
steps:
  - name: test
    image: alpine
    file:
      path: /tmp/Dockerfile
      content: |-
        FROM alpine
        RUN apk add --update-cache --no-cache git
```

**Comment by nicholasdille** [comment]
Move spec to top level:

```yaml
files:
  inject:
    -... 
```
