### ISSUE TITLE
Native support for Docker build? 

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/insulatr#37]
Build type like:

```yaml
steps:
  - name: build
    image: new/image:name
    build:
      file: ./Dockerfile
      context: .
```

- Overload existing build step
- Fields `build` and `commands` are mutually exclusive
- Use `environment` as builds arguments? Or place under `build`?
- Support for build secrets
- Support access to services
