### ISSUE TITLE
Unify file injection and creation

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/insulatr#39]
Like so:

```yaml
files:
  - inject: *.jar
  - new: abc.yaml
    content: |-
      Line1
      Line2
```
