### ISSUE TITLE
Import existing environment variables

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/insulatr#4]
If an environment variable exist in the context of `insulatr`, it can be made available to build steps using the following syntax:

```
steps:
  - name: test
    image: alpine
    environment:
      - PS1
      - PROMPT
```

The same should work for global environment variables (#5).
