### ISSUE TITLE
Simplify file injection 

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/insulatr#42]
Injection and creation can be told apart using content field:

```yaml
files:
  - inject: injected.file
  - inject: created.file
    content: newfile.data
  - extract: artifact.file
```
