### ISSUE TITLE
Add global environment variables

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/insulatr#5]
Global environment variables apply to all build steps. The following build definition must display `name1` and `name2`:

```
environment:
  - name1: value1
  - name2: value2

steps:
  - name: test
    image: alpine
    commands:
      - printenv
```

- [ ] Implement
- [ ] Add from environment of `insulatr`
- [ ] Add to all build steps
- [ ] Explicitly add to services like vars from environment
- [ ] Update documentation
